######################################################################
# Automatically generated by qmake (3.0) ti elo 16 00:18:12 2016
######################################################################

QT += widgets testlib
TEMPLATE = app

TARGET = test
INCLUDEPATH += "../src"

# Input
HEADERS += EmployeeControllerTest.h
SOURCES += RunTests.cpp \
            EmployeeControllerTest.cpp
