######################################################################
# Automatically generated by qmake (3.0) ti elo 16 23:35:17 2016
######################################################################

QT += testlib core gui widgets
TEMPLATE = app
TARGET = test
INCLUDEPATH += ../src/controller \
               ../src/model \
               ../src/view \
               ../src/main

# Input
HEADERS += ../src/controller/EmployeeController.h \
           ../src/controller/IObserver.h \
           ../src/controller/EmployeeControllerException.h \
           ../src/model/Employee.h \
           ../src/model/EmployeeFactory.h \
           ../src/model/HourlyPaidEmployee.h \
           ../src/model/MonthlyPaidEmployee.h \
           ../src/model/SalesmanEmployee.h \
           ../src/view/EmployeeView.h
SOURCES += ../src/controller/EmployeeController.cpp \
           EmployeeControllerTest.cpp \
           ../src/model/Employee.cpp \
           ../src/model/EmployeeFactory.cpp \
           ../src/model/HourlyPaidEmployee.cpp \
           ../src/model/MonthlyPaidEmployee.cpp \
           ../src/model/SalesmanEmployee.cpp \
           ../src/view/EmployeeView.cpp
