######################################################################
# Automatically generated by qmake (3.0) ti elo 16 23:35:17 2016
######################################################################

QT += testlib core gui widgets
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
HEADERS += ../src/EmployeeController.h \
           ../src/EmployeeView.h \
           ../src/Employee.h \
           ../src/MonthlyPaidEmployee.h \
           ../src/HourlyPaidEmployee.h \
           ../src/SalesmanEmployee.h \
           ../src/IObserver.h \
           ../src/EmployeeFactory.h
SOURCES += EmployeeControllerTest.cpp \
           ../src/EmployeeController.cpp \
           ../src/EmployeeView.cpp \
           ../src/Employee.cpp \
           ../src/MonthlyPaidEmployee.cpp \
           ../src/HourlyPaidEmployee.cpp \
           ../src/SalesmanEmployee.cpp \
           ../src/EmployeeFactory.cpp
