######################################################################
# Automatically generated by qmake (3.0) pe elo 12 20:14:51 2016
######################################################################

QT += widgets

TEMPLATE = app
TARGET = salary-administration-gui
INCLUDEPATH += .

# Input
HEADERS += SalaryAdministrationGui/minimal/main.h \
           SalaryAdministrationGui/src/Employee.h \
           SalaryAdministrationGui/src/EmployeeController.h \
           SalaryAdministrationGui/src/EmployeeFactory.h \
           SalaryAdministrationGui/src/EmployeeView.h \
           SalaryAdministrationGui/src/HourlyPaidEmployee.h \
           SalaryAdministrationGui/src/MonthlyPaidEmployee.h \
           SalaryAdministrationGui/src/SalesmanEmployee.h \
    SalaryAdministrationGui/src/testEmployeeController.cpp_disabled
SOURCES += SalaryAdministrationGui/minimal/main.cpp \
           SalaryAdministrationGui/src/Employee.cpp \
           SalaryAdministrationGui/src/EmployeeController.cpp \
           SalaryAdministrationGui/src/EmployeeFactory.cpp \
           SalaryAdministrationGui/src/EmployeeView.cpp \
           SalaryAdministrationGui/src/HourlyPaidEmployee.cpp \
           SalaryAdministrationGui/src/MonthlyPaidEmployee.cpp \
           SalaryAdministrationGui/src/SalesmanEmployee.cpp
